### ISSUE TITLE
Onboarding iosxr device

### ISSUE THREAD

**Issue by Kani999** [networktocode/ntc-netbox-plugin-onboarding#139]
### Environment
* Python version: 3.8.5
* NetBox version:  v2.10.10
* ntc-netbox-plugin-onboarding version:  2.1.0

### Steps to Reproduce
1. Opens `/plugins/onboarding/` path
2. Add iosxr device
3. OnboardingException occurs: `OnboardException: fail-connect: ERROR: Error reading SSH protocol banner`

### Expected Behavior
Device onboards successfully

### Observed Behavior
Onboarding plugin fails. 

---

I found that Paramiko has setting for banner_timeout, (`banner_timeout=200`) But I didn't find something similar for napalm.
Is that common issue, or is something specific for me.

---

```log
default: netbox_onboarding.worker.onboard_device(314, *Credentials argument hidden*) (e26001e4-3947-4e6b-a070-81578a191d93)
START: onboard device
Getting device with IP lookup failed: Device matching query does not exist.
CHECK: IP xxx.xxx.xxx.xxx:22
COLLECT: device information xxx.xxx.xxx.xx
INFO guessing device type: xxx.xxx.xxx.xx
starting thread (client mode): 0x60998280
Local version/idstring: SSH-2.0-paramiko_2.7.2

Exception: Error reading SSH protocol banner
Traceback (most recent call last):
File "/opt/netbox/venv/lib/python3.8/site-packages/paramiko/transport.py", line 2211, in _check_banner
buf = self.packetizer.readline(timeout)
File "/opt/netbox/venv/lib/python3.8/site-packages/paramiko/packet.py", line 380, in readline
buf += self._read_timeout(timeout)
File "/opt/netbox/venv/lib/python3.8/site-packages/paramiko/packet.py", line 609, in _read_timeout

raise EOFError()
EOFError

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/netbox/venv/lib/python3.8/site-packages/paramiko/transport.py", line 2039, in run
self._check_banner()
File "/opt/netbox/venv/lib/python3.8/site-packages/paramiko/transport.py", line 2215, in _check_banner
raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

ERROR: Error reading SSH protocol banner
OnboardException: fail-general: OnboardException: fail-connect: ERROR: Error reading SSH protocol banner
default: Job OK (e26001e4-3947-4e6b-a070-81578a191d93)
Result is kept for 500 seconds
```

**Comment by Kani999** [comment]
- https://github.com/networktocode/ntc-netbox-plugin-onboarding/blob/2eca893c2e97ed40f2b2c45ef3be93c0d120b6fc/netbox_onboarding/onboard.py#L101
- I'm also passing `NAPALM_ARGS = {'global_delay_factor':300, 'banner_timeout':300, 'conn_timeout':300}` as the env variable
- So timeouts should be fine.

**Comment by Kani999** [comment]
- Increasing `rate-limit` (from 60 to 120) on the **network device** solved the problem.
